package com.example.demo.entities;
// Generated Dec 14, 2016 3:47:47 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblCompany generated by hbm2java
 */
@Entity
@Table(name = "tbl_company", catalog = "quanlybaohiem")
public class TblCompany{

	private int companyInternalId;
	private String companyName;
	private String address;
	private String email;
	private String telephone;
	private Set<TblUser> tblUsers = new HashSet<TblUser>(0);

	public TblCompany() {
	}

	public TblCompany(int companyInternalId, String companyName, String address) {
		this.companyInternalId = companyInternalId;
		this.companyName = companyName;
		this.address = address;
	}

	public TblCompany(int companyInternalId, String companyName, String address, String email, String telephone,
			Set<TblUser> tblUsers) {
		this.companyInternalId = companyInternalId;
		this.companyName = companyName;
		this.address = address;
		this.email = email;
		this.telephone = telephone;
		this.tblUsers = tblUsers;
	}

	@Id
	@Column(name = "company_internal_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getCompanyInternalId() {
		return this.companyInternalId;
	}

	public void setCompanyInternalId(int companyInternalId) {
		this.companyInternalId = companyInternalId;
	}

	@Column(name = "company_name", nullable = false, length = 50)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "address", nullable = false, length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telephone", length = 15)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblCompany")
	public Set<TblUser> getTblUsers() {
		return this.tblUsers;
	}

	public void setTblUsers(Set<TblUser> tblUsers) {
		this.tblUsers = tblUsers;
	}

}
