package com.example.demo.entities;
// Generated Dec 14, 2016 3:47:47 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblInsurance generated by hbm2java
 */
@Entity
@Table(name = "tbl_insurance", catalog = "quanlybaohiem")
public class TblInsurance{

	private int insuranceInternalId;
	private String insuranceNumber;
	private String insuranceStartDate;
	private String insuranceEndDate;
	private String placeOfRegister;
	private Set<TblUser> tblUsers = new HashSet<TblUser>(0);

	public TblInsurance() {
	}

	public TblInsurance(int insuranceInternalId, String insuranceNumber, String insuranceStartDate,
			String placeOfRegister) {
		this.insuranceInternalId = insuranceInternalId;
		this.insuranceNumber = insuranceNumber;
		this.insuranceStartDate = insuranceStartDate;
		this.placeOfRegister = placeOfRegister;
	}

	public TblInsurance(int insuranceInternalId, String insuranceNumber, String insuranceStartDate, String insuranceEndDate,
			String placeOfRegister, Set<TblUser> tblUsers) {
		this.insuranceInternalId = insuranceInternalId;
		this.insuranceNumber = insuranceNumber;
		this.insuranceStartDate = insuranceStartDate;
		this.insuranceEndDate = insuranceEndDate;
		this.placeOfRegister = placeOfRegister;
		this.tblUsers = tblUsers;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "insurance_internal_id", unique = true, nullable = false)
	public int getInsuranceInternalId() {
		return this.insuranceInternalId;
	}

	public void setInsuranceInternalId(int insuranceInternalId) {
		this.insuranceInternalId = insuranceInternalId;
	}

	@Column(name = "insurance_number", nullable = false, length = 10)
	public String getInsuranceNumber() {
		return this.insuranceNumber;
	}

	public void setInsuranceNumber(String insuranceNumber) {
		this.insuranceNumber = insuranceNumber;
	}

	@Column(name = "insurance_start_date", nullable = false, length = 10)
	public String getInsuranceStartDate() {
		return this.insuranceStartDate;
	}

	public void setInsuranceStartDate(String insuranceStartDate) {
		this.insuranceStartDate = insuranceStartDate;
	}

	@Column(name = "insurance_end_date", length = 10)
	public String getInsuranceEndDate() {
		return this.insuranceEndDate;
	}

	public void setInsuranceEndDate(String insuranceEndDate) {
		this.insuranceEndDate = insuranceEndDate;
	}

	@Column(name = "place_of_register", nullable = false, length = 50)
	public String getPlaceOfRegister() {
		return this.placeOfRegister;
	}

	public void setPlaceOfRegister(String placeOfRegister) {
		this.placeOfRegister = placeOfRegister;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblInsurance")
	public Set<TblUser> getTblUsers() {
		return this.tblUsers;
	}

	public void setTblUsers(Set<TblUser> tblUsers) {
		this.tblUsers = tblUsers;
	}

}
