package com.example.demo.entities;
// Generated Dec 14, 2016 3:47:47 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblUser generated by hbm2java
 */
@Entity
@Table(name = "tbl_user", catalog = "quanlybaohiem")
public class TblUser{

	private int userInternalId;
	private TblCompany tblCompany;
	private TblInsurance tblInsurance;
	private String userName;
	private String userPassword;
	private String userFullName;
	private String userSexDivision;
	private String birthday;

	public TblUser() {
	}

	public TblUser(int userInternalId, TblCompany tblCompany, TblInsurance tblInsurance, String userName,
			String userPassword, String userFullName, String userSexDivision) {
		this.userInternalId = userInternalId;
		this.tblCompany = tblCompany;
		this.tblInsurance = tblInsurance;
		this.userName = userName;
		this.userPassword = userPassword;
		this.userFullName = userFullName;
		this.userSexDivision = userSexDivision;
	}

	public TblUser(int userInternalId, TblCompany tblCompany, TblInsurance tblInsurance, String userName,
			String userPassword, String userFullName, String userSexDivision, String birthday) {
		this.userInternalId = userInternalId;
		this.tblCompany = tblCompany;
		this.tblInsurance = tblInsurance;
		this.userName = userName;
		this.userPassword = userPassword;
		this.userFullName = userFullName;
		this.userSexDivision = userSexDivision;
		this.birthday = birthday;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "user_internal_id", unique = true, nullable = false)
	public int getUserInternalId() {
		return this.userInternalId;
	}

	public void setUserInternalId(int userInternalId) {
		this.userInternalId = userInternalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_internal_id", nullable = false)
	public TblCompany getTblCompany() {
		return this.tblCompany;
	}

	public void setTblCompany(TblCompany tblCompany) {
		this.tblCompany = tblCompany;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "insurance_internal_id", nullable = false)
	public TblInsurance getTblInsurance() {
		return this.tblInsurance;
	}

	public void setTblInsurance(TblInsurance tblInsurance) {
		this.tblInsurance = tblInsurance;
	}

	@Column(name = "user_name", nullable = false, length = 15)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_password", nullable = false, length = 32)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "user_full_name", nullable = false, length = 50)
	public String getUserFullName() {
		return this.userFullName;
	}

	public void setUserFullName(String userFullName) {
		this.userFullName = userFullName;
	}

	@Column(name = "user_sex_division", nullable = false, length = 2)
	public String getUserSexDivision() {
		return this.userSexDivision;
	}

	public void setUserSexDivision(String userSexDivision) {
		this.userSexDivision = userSexDivision;
	}
	@Column(name = "birthday", length = 10)
	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

}
